# path
path_meta: /Users/eirikhoy/Dropbox/projects/airr_comet/data/msi_crc_pd1/metadata.txt
path_data: /Users/eirikhoy/Dropbox/projects/airr_comet/data/msi_crc_pd1/
path_results: results/msi_crc_pd1

# sample colname
sample_column: sample_name
